name: 🤖 AI Integration Issue
description: Issues with AI assistant integration
title: "[AI]: "
labels: ["ai-integration"]
body:
  - type: textarea
    id: problem
    attributes:
      label: What's the issue?
      placeholder: "When I ask Claude to analyze my code using In-Memoria tools..."
    validations:
      required: true

  - type: textarea
    id: setup
    attributes:
      label: Your setup
      placeholder: |
        - Using: Claude Desktop/Code/Other
        - Has project been learned? Yes/No
        - Error logs (if any)
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What should happen instead?
      placeholder: "Claude should have used In-Memoria's insights to..."