name: ✨ Feature Request
description: Suggest a new feature for In-Memoria
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: What feature would you like?
      placeholder: Describe the feature you'd like to see...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: What problem would this solve?
      placeholder: "Currently I have to... but it would be better if..."
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      placeholder: Any other details or examples...