name: 🚀 Performance Issue
description: Report performance problems
title: "[Performance]: "
labels: ["performance"]
body:
  - type: textarea
    id: performance-issue
    attributes:
      label: What's slow?
      placeholder: "The `learn` command takes 10+ minutes on my codebase..."
    validations:
      required: true

  - type: textarea
    id: project-info
    attributes:
      label: Project details
      placeholder: |
        - ~5,000 files, 500k lines
        - Languages: TypeScript, Python
        - Takes: 15 minutes
    validations:
      required: true

  - type: textarea
    id: system-info
    attributes:
      label: System specs
      placeholder: "16 cores, 32GB RAM, SSD"